export default {
    HOME: 'HOME',
    LOGOUT: 'LOGOUT',
    LOGIN: 'LOGIN',
    RECUPERARSENHA: 'RECUPERARSENHA',
    ESQUECERSENHA: 'ESQUECERSENHA',
    TELAINICIAL: 'TELAINICIAL',
    CADASTROINICIAL: 'CADASTROINICIAL',
    CADASTRO: 'CADASTRO',
    
    MOSTRARUSUARIO: 'MOSTRARUSUARIO',
    PESQUISARMENSAGENS: 'PESQUISARMENSAGENS',
    PESQUISARUSUARIOS: 'PESQUISARUSUARIOS',
    EDITARPERFIL: 'EDITARPERFIL',
    MENSAGENSENVIADAS: 'MENSAGENSENVIADAS',
    MENSAGENSRECEBIDAS: 'MENSAGENSRECEBIDAS',
    TODASMENSAGENS: 'TODASMENSAGENS'
}