export default {
    HOME: 'HOME',
    LOGOUT: 'LOGOUT',
    LOGIN: 'LOGIN',
    RECUPERARSENHA: 'RECUPERARSENHA',
    ESQUECERSENHA: 'ESQUECERSENHA',
    TELAINICIAL: 'TELAINICIAL',
    CADASTROINICIAL: 'CADASTROINICIAL',
    CADASTRO: 'CADASTRO',
    MEUSPACIENTES: 'MEUSPACIENTES',
    VINCULARPACIENTES: 'VINCULARPACIENTES'
}